csp_user:
    resource: "@CSPUserBundle/Resources/config/routing.yml"
    prefix:   /

csp_comic:
    resource: "@CSPComicBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: CSPUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout