# app/config/security.yml

security:
    encoders:
        CSP\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

         # … le pare-feu « dev »
        # Firewall principal pour le reste de notre site
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                csrf_provider:       form.csrf_provider
                login_path:          fos_user_security_login
                check_path:          fos_user_security_check
            logout:       true
            logout:
                path:   /logout
                target: /login
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }