csp_comic_homepage:
    path:     /hello/{name}
    defaults: { _controller: CSPComicBundle:Default:index }

hello_the_world:
    path:     /index
    defaults: { _controller: CSPComicBundle:Index:index }

