csp_comic_homepage:
    path:     /	
    defaults: { _controller: CSPComicBundle:Index:index }

csp_comic_upload:
    path:     /upload
    defaults: { _controller: CSPComicBundle:Index:upload }

csp_comic_personnal:
    path:     /personnal
    defaults: { _controller: CSPComicBundle:Index:personnal }

csp_comic_comic:
    path:     /comic/{id}
    defaults: { _controller: CSPComicBundle:Index:comic }

csp_comic_comics:
    path:     /comics
    defaults: { _controller: CSPComicBundle:Index:comics }
