<?php

namespace CSP\ComicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComicRepository extends EntityRepository
{
}
